# Generated by Django 2.0 on 2017-12-27 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20171224_0922'),
        ('transcations', '0008_auto_20171223_1518'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendsUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_related', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transcations.Person')),
                ('store_related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Store')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='costumeraccount',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ονομα'),
        ),
        migrations.AlterField(
            model_name='costumeraccount',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Επίθετο'),
        ),
    ]
