# Generated by Django 2.0 on 2018-05-14 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
        ('dashboard', '0001_initial'),
        ('transcations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendsuser',
            name='person_related',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transcations.Person'),
        ),
        migrations.AddField(
            model_name='extendsuser',
            name='store_related',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Store'),
        ),
        migrations.AddField(
            model_name='extendsuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
