# Generated by Django 2.0 on 2018-06-07 11:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedCostInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=64, verbose_name='Αρ.Παραστατικού/Σχολιασμός')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Ημερομηνία Δημιουργίας')),
                ('date_expired', models.DateField(default=django.utils.timezone.now, verbose_name='Ημερομηνία Λήξης')),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=50, verbose_name='Aξία Παραστατικού')),
                ('paid_value', models.DecimalField(decimal_places=2, default=0, max_digits=50, verbose_name='Πληρωμένη Αξία')),
                ('payment_method', models.CharField(choices=[('1', 'Μετρητά'), ('2', 'Τραπεζική Κατάθεση'), ('3', 'Πιστωτική Κάρτα'), ('4', 'Paypal')], default='1', max_length=1)),
                ('is_paid', models.BooleanField(default=False, verbose_name='Είναι πληρωμένο')),
            ],
            options={
                'verbose_name_plural': '3. Εντολές Πληρωμών',
                'ordering': ['is_paid', '-date_expired'],
            },
        ),
        migrations.CreateModel(
            name='FixedCosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Δημιουργία Κεντρικής Κατηγορίας',
                'verbose_name_plural': '1. Κεντρική Κατηγορία Εξόδων',
            },
        ),
        migrations.CreateModel(
            name='FixedCostsItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True, verbose_name='Ονομασία Κατηγορίας')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcations.FixedCosts')),
                ('store_related', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Store')),
            ],
            options={
                'verbose_name': 'Δημιουργία Λογαριασμού',
                'verbose_name_plural': '2. Λογαριασμοί και Πάγια έξοδα',
            },
        ),
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Απασχόληση')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Σημειώσεις')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=50, verbose_name='Υπόλοιπο')),
            ],
            options={
                'verbose_name_plural': '5. Απασχόληση',
            },
        ),
        migrations.CreateModel(
            name='PayrollInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(blank=True, max_length=64, null=True, verbose_name='Περιγραφή')),
                ('category', models.CharField(choices=[('1', 'Μισθός'), ('2', 'ΙΚΑ'), ('3', 'ΑΣΦΑΛΙΣΤΙΚΕΣ ΕΙΣΦΟΡΕΣ'), ('4', 'ΗΜΕΡΟΜΗΣΘΙΟ'), ('5', 'ΕΡΓΟΣΗΜΟ'), ('6', 'ΔΩΡΟ')], default='1', max_length=1)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=50, verbose_name='Αξία')),
                ('date_created', models.DateField(auto_now=True)),
                ('date_expired', models.DateField(default=django.utils.timezone.now, verbose_name='Πληρωμή μέχρι .....')),
                ('paid_value', models.DecimalField(decimal_places=2, default=0, max_digits=50, verbose_name='Πιστωτικό Υπόλοιπο')),
                ('payment_method', models.CharField(choices=[('1', 'Μετρητά'), ('2', 'Τραπεζική Κατάθεση'), ('3', 'Πιστωτική Κάρτα'), ('4', 'Paypal')], default='1', max_length=1)),
                ('is_paid', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': '7. Εντολές Πληρωμής Υπαλλήλων. ',
                'ordering': ['is_paid', '-date_expired'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=64, unique=True, verbose_name='Ονοματεπώνυμο')),
                ('phone', models.CharField(blank=True, max_length=10, verbose_name='Τηλέφωνο')),
                ('phone1', models.CharField(blank=True, max_length=10, verbose_name='Κινητό')),
                ('date_added', models.DateField(default=django.utils.timezone.now, verbose_name='Ημερομηνία Πρόσληψης')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=50, verbose_name='Υπόλοιπο')),
                ('occupation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcations.Occupation', verbose_name='Απασχόληση')),
                ('store_related', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Store')),
            ],
            options={
                'verbose_name_plural': '6. Υπάλληλος',
            },
        ),
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_started', models.DateField()),
                ('date_end', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='VacationReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='vacation',
            name='reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcations.VacationReason'),
        ),
        migrations.AddField(
            model_name='vacation',
            name='staff_related',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcations.Person'),
        ),
        migrations.AddField(
            model_name='payrollinvoice',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcations.Person', verbose_name='Υπάλληλος'),
        ),
        migrations.AddField(
            model_name='fixedcostinvoice',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcations.FixedCostsItem', verbose_name='Λογαριασμός'),
        ),
    ]
