# Generated by Django 2.0 on 2018-06-07 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transcations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacation',
            name='notes',
            field=models.CharField(default='11', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vacation',
            name='reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transcations.VacationReason'),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='staff_related',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacations', to='transcations.Person'),
        ),
    ]
