# Generated by Django 2.0 on 2017-12-19 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transcations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedCostInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=64, verbose_name='Αρ.Παραστατικού/Σχολιασμός')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Ημερομηνία Δημιουργίας')),
                ('date_expired', models.DateField(default=django.utils.timezone.now, verbose_name='Ημερομηνία Λήξης')),
                ('price', models.DecimalField(decimal_places=2, max_digits=50, verbose_name='Aξία Παραστατικού')),
                ('paid_value', models.DecimalField(decimal_places=2, default=0, max_digits=50, verbose_name='Πληρωμένη Αξία')),
                ('payment_method', models.CharField(choices=[('1', 'Μετρητά'), ('2', 'Τραπεζική Κατάθεση'), ('3', 'Πιστωτική Κάρτα'), ('4', 'Paypal')], max_length=1)),
                ('is_paid', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Εντολές Πληρωμών',
            },
        ),
        migrations.CreateModel(
            name='FixedCosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
            ],
            options={
                'verbose_name': 'Κεντρική Κατηγορία Εξόδων   ',
            },
        ),
        migrations.CreateModel(
            name='FixedCostsItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True, verbose_name='Ονομασία Κατηγορίας')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcations.FixedCosts')),
            ],
            options={
                'verbose_name': 'Λογαριασμοί και Πάγια έξοδα',
            },
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('shop_related', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PayrollInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(blank=True, max_length=64, null=True, verbose_name='Περιγραφή')),
                ('category', models.CharField(choices=[('1', 'Μισθός'), ('2', 'ΙΚΑ'), ('3', 'ΑΣΦΑΛΙΣΤΙΚΕΣ ΕΙΣΦΟΡΕΣ'), ('4', 'ΗΜΕΡΟΜΗΣΘΙΟ'), ('5', 'ΕΡΓΟΣΗΜΟ')], default='1', max_length=1)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=50, verbose_name='Αξία')),
                ('date_added', models.DateField(auto_now=True)),
                ('date_expired', models.DateField(default=django.utils.timezone.now, verbose_name='Πληρωμή μέχρι .....')),
                ('paid_value', models.DecimalField(decimal_places=2, default=0, max_digits=50, verbose_name='Πιστωτικό Υπόλοιπο')),
                ('payment_method', models.CharField(choices=[('1', 'Μετρητά'), ('2', 'Τραπεζική Κατάθεση'), ('3', 'Πιστωτική Κάρτα'), ('4', 'Paypal')], max_length=1)),
                ('is_paid', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Εντολές Πληρωμής Υπαλλήλων. ',
            },
        ),
        migrations.RemoveField(
            model_name='createpersonsalarycost',
            name='category',
        ),
        migrations.RemoveField(
            model_name='createpersonsalarycost',
            name='person',
        ),
        migrations.RemoveField(
            model_name='fixed_costs_item',
            name='category',
        ),
        migrations.RemoveField(
            model_name='order_fixed_cost',
            name='category',
        ),
        migrations.RemoveField(
            model_name='pagia_exoda',
            name='category',
        ),
        migrations.RemoveField(
            model_name='pagia_exoda_order',
            name='category',
        ),
        migrations.RemoveField(
            model_name='pagia_exoda_order',
            name='person',
        ),
        migrations.RemoveField(
            model_name='pagia_exoda_pay_order',
            name='person',
        ),
        migrations.DeleteModel(
            name='PayOrderFixedCost',
        ),
        migrations.RemoveField(
            model_name='paypersonsalarycost',
            name='category',
        ),
        migrations.RemoveField(
            model_name='paypersonsalarycost',
            name='person',
        ),
        migrations.RemoveField(
            model_name='personhourscreate',
            name='person',
        ),
        migrations.RemoveField(
            model_name='personhourspay',
            name='person',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='date_joined',
            new_name='date_added',
        ),
        migrations.RemoveField(
            model_name='occupation',
            name='category',
        ),
        migrations.AlterField(
            model_name='occupation',
            name='title',
            field=models.CharField(max_length=64, verbose_name='Απασχόληση'),
        ),
        migrations.DeleteModel(
            name='CategoryPersonPay',
        ),
        migrations.DeleteModel(
            name='CreatePersonSalaryCost',
        ),
        migrations.DeleteModel(
            name='Fixed_costs',
        ),
        migrations.DeleteModel(
            name='Fixed_Costs_item',
        ),
        migrations.DeleteModel(
            name='Order_Fixed_Cost',
        ),
        migrations.DeleteModel(
            name='Pagia_Exoda',
        ),
        migrations.DeleteModel(
            name='Pagia_Exoda_Order',
        ),
        migrations.DeleteModel(
            name='Pagia_Exoda_Pay_Order',
        ),
        migrations.DeleteModel(
            name='PayPersonSalaryCost',
        ),
        migrations.DeleteModel(
            name='PersonHoursCreate',
        ),
        migrations.DeleteModel(
            name='PersonHoursPay',
        ),
        migrations.DeleteModel(
            name='PersonMastoras',
        ),
        migrations.AddField(
            model_name='payrollinvoice',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcations.Person', verbose_name='Υπάλληλος'),
        ),
        migrations.AddField(
            model_name='fixedcostinvoice',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcations.FixedCostsItem', verbose_name='Λογαριασμός'),
        ),
        migrations.AddField(
            model_name='occupation',
            name='payroll_related',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transcations.Payroll'),
        ),
    ]
