# Generated by Django 2.0 on 2017-12-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcations', '0003_auto_20171219_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occupation',
            name='remaining_cost',
        ),
        migrations.RemoveField(
            model_name='occupation',
            name='total_cost',
        ),
        migrations.AddField(
            model_name='occupation',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50, verbose_name='Υπόλοιπο'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50, verbose_name='Υπόλοιπο'),
        ),
    ]
