# Generated by Django 2.0 on 2017-12-21 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcations', '0004_auto_20171219_1643'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fixedcostinvoice',
            options={'ordering': ['is_paid', 'date_expired'], 'verbose_name_plural': '3. Εντολές Πληρωμών'},
        ),
    ]
