# Generated by Django 2.0 on 2017-12-23 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_store'),
        ('transcations', '0005_auto_20171221_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='shop_related',
        ),
        migrations.RemoveField(
            model_name='occupation',
            name='payroll_related',
        ),
        migrations.AddField(
            model_name='fixedcostsitem',
            name='store_related',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Store'),
        ),
        migrations.AddField(
            model_name='person',
            name='store_related',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Store'),
        ),
        migrations.DeleteModel(
            name='Payroll',
        ),
    ]
