# Generated by Django 2.0 on 2017-12-23 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcations', '0006_auto_20171223_1029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payrollinvoice',
            options={'ordering': ['is_paid', '-date_expired'], 'verbose_name_plural': '7. Εντολές Πληρωμής Υπαλλήλων. '},
        ),
        migrations.AlterField(
            model_name='payrollinvoice',
            name='category',
            field=models.CharField(choices=[('1', 'Μισθός'), ('2', 'ΙΚΑ'), ('3', 'ΑΣΦΑΛΙΣΤΙΚΕΣ ΕΙΣΦΟΡΕΣ'), ('4', 'ΗΜΕΡΟΜΗΣΘΙΟ'), ('5', 'ΕΡΓΟΣΗΜΟ'), ('6', 'ΔΩΡΟ')], default='1', max_length=1),
        ),
    ]
