# Generated by Django 2.0 on 2017-12-31 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcations', '0009_auto_20171228_0946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payrollinvoice',
            old_name='date_added',
            new_name='date_created',
        ),
    ]
