# Generated by Django 2.0.3 on 2018-03-26 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcations', '0010_auto_20171231_0921'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fixedcosts',
            options={'verbose_name': 'Δημιουργία Κεντρικής Κατηγορίας', 'verbose_name_plural': '1. Κεντρική Κατηγορία Εξόδων'},
        ),
        migrations.AlterModelOptions(
            name='fixedcostsitem',
            options={'verbose_name': 'Δημιουργία Λογαριασμού', 'verbose_name_plural': '2. Λογαριασμοί και Πάγια έξοδα'},
        ),
    ]
