# Generated by Django 2.0 on 2018-06-07 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('site_active', models.BooleanField(default=False)),
                ('additional_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('limit_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_expired', models.DateField(auto_created=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('bank', models.CharField(choices=[('0', 'No Bank'), ('1', 'Εθνική Τράπεζα'), ('2', 'Τράπεζα Πειραιώς'), ('3', 'Interamerican')], default='0', max_length=1)),
                ('is_expense', models.BooleanField(default=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('payment_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.PaymentMethod')),
            ],
            options={
                'ordering': ['-date_expired'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('margin', models.IntegerField(default=0)),
                ('markup', models.IntegerField(default=0)),
            ],
        ),
    ]
