# Generated by Django 2.0 on 2017-12-22 13:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_expired', models.DateField(default=datetime.datetime(2017, 12, 22, 15, 22, 50, 440647))),
                ('payment_type', models.CharField(choices=[('1', 'Μετρητά'), ('2', 'Τραπεζική Κατάθεση'), ('3', 'Πιστωτική Κάρτα'), ('4', 'Paypal')], default='1', max_length=1)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('bank', models.CharField(choices=[('0', 'No Bank'), ('1', 'Εθνική Τράπεζα'), ('2', 'Τράπεζα Πειραιώς'), ('3', 'Interamerican')], default='0', max_length=1)),
                ('is_paid', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('is_expense', models.BooleanField(default=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
    ]
