# Generated by Django 2.0 on 2017-12-22 13:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentorders',
            name='date_expired',
            field=models.DateField(default=datetime.datetime(2017, 12, 22, 13, 23, 32, 757243, tzinfo=utc)),
        ),
    ]
