# Generated by Django 2.0 on 2017-12-22 14:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20171222_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentorders',
            name='date_expired',
            field=models.DateField(default=datetime.datetime(2017, 12, 22, 14, 1, 2, 409825, tzinfo=utc)),
        ),
    ]
