# Generated by Django 2.0 on 2017-12-31 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20171224_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentorders',
            name='date_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
