# Generated by Django 2.0 on 2018-01-07 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_paymentorders_date_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentorders',
            options={'ordering': ['-date_expired']},
        ),
    ]
