# Generated by Django 2.0.2 on 2018-05-03 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_paymentmethod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentorders',
            name='payment_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.PaymentMethod'),
        ),
    ]
