# Generated by Django 2.0 on 2018-05-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20180503_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='additional_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='limit_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
