# Generated by Django 2.0 on 2018-06-07 11:07

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RetailOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Αξία Παραγγελίας')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Έκπτωση')),
                ('taxes', models.CharField(choices=[('1', '13'), ('2', '23'), ('3', '24'), ('4', '0')], default='3', max_length=1)),
                ('paid_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Αποπληρωμένο Πόσο')),
                ('final_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('count_items', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('1', 'Νέα Παραγγελία'), ('2', 'Σε Επεξεργασία'), ('3', 'Έτοιμο προς Αποστολή'), ('4', 'Απεστάλη'), ('5', 'Επιστράφηκε'), ('6', 'Ακυρώθηκε'), ('7', 'Εισπράκτηκε'), ('8', 'Ολοκληρώθηκε')], default='1', max_length=1)),
                ('order_type', models.CharField(choices=[('r', 'Λιανική Πώληση'), ('e', 'Eshop'), ('b', 'Επιστροφές'), ('d', 'Καταστροφή Προϊόντων'), ('wa', 'Παραστατικό Εισαγωγής'), ('wr', 'Παραστατικό Εξαγωγής')], default='r', max_length=1)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Συνολικό Κόστος Παραγγελίας')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('payment_cost', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('day_sent', models.DateTimeField(blank=True, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Όνομα')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Έπίθετο')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Πόλη')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Διεύθυνση')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='Νομός')),
                ('zip_code', models.IntegerField(blank=True, null=True, verbose_name='ΤΚ')),
                ('cellphone', models.CharField(blank=True, max_length=10, null=True, verbose_name='Κινητό')),
                ('phone', models.CharField(blank=True, max_length=10, null=True, verbose_name='Σταθερό Τηλεφωνο')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('costumer_submit', models.BooleanField(default=True, verbose_name='Επιβεβαίωση')),
                ('eshop_order_id', models.CharField(blank=True, max_length=10, null=True)),
                ('eshop_session_id', models.CharField(blank=True, max_length=50, null=True)),
                ('printed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': '1. Παραστατικά Πωλήσεων',
            },
            managers=[
                ('my_query', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='RetailOrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Τιμή Μονάδας')),
                ('qty', models.DecimalField(decimal_places=2, default=1, max_digits=6, verbose_name='Ποσότητα')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Τιμή Μονάδας Με έκπτωση.')),
                ('final_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('is_find', models.BooleanField(default=False)),
                ('is_return', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='point_of_sale.RetailOrder')),
            ],
            options={
                'verbose_name_plural': '2. Προϊόντα Πωληθέντα',
            },
            managers=[
                ('my_query', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('content', models.CharField(default='Input here', max_length=300)),
                ('active', models.BooleanField(default=True)),
                ('ordering', models.IntegerField(default=1)),
                ('for_site', models.BooleanField(default=True, verbose_name='Ενεργό για το Site')),
                ('value', models.DecimalField(decimal_places=2, default=5, max_digits=5)),
                ('value_limit', models.DecimalField(decimal_places=2, default=40, max_digits=5)),
            ],
            options={
                'verbose_name_plural': 'Τρόποι Αποστολής',
                'ordering': ['ordering'],
            },
        ),
    ]
