# Generated by Django 2.0 on 2017-12-16 10:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import point_of_sale.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_auto_20171216_1039'),
        ('inventory_manager', '0005_auto_20171216_1218'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestroyOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=point_of_sale.models.create_destroy_title, max_length=15)),
                ('day_added', models.DateTimeField(auto_now=True)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('notes', models.CharField(blank=True, max_length=150, null=True)),
                ('seller_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DestroyOrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('qty', models.DecimalField(decimal_places=3, default=1, max_digits=10)),
                ('day_added', models.DateField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='point_of_sale.DestroyOrder')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.SizeAttribute')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, unique=True)),
                ('sort_id', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['sort_id'],
            },
        ),
        migrations.CreateModel(
            name='RetailOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=datetime.datetime(2017, 12, 16, 12, 18, 53, 683386), verbose_name='Ημερομηνία Δημιουργίας')),
                ('date_edited', models.DateTimeField(auto_now=True, verbose_name='Ημερομηνία Επεξεργασίας')),
                ('order_type', models.CharField(choices=[('r', 'Λιανική Πώληση'), ('e', 'Eshop'), ('b', 'Επιστροφές'), ('d', 'Καταστροφή Προϊόντων')], max_length=1)),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Τίτλος')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Έκπτωση')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Αξία Παραγγελίας')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Συνολικό Κόστος Παραγγελίας')),
                ('paid_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Αποπληρωμένο Πόσο')),
                ('taxes', models.IntegerField(default=24, verbose_name='Ποσοστό Φόρου')),
                ('final_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('count_items', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('payment_cost', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('day_sent', models.DateTimeField(blank=True, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Όνομα')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Έπίθετο')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Πόλη')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Διεύθυνση')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='Νομός')),
                ('zip_code', models.IntegerField(blank=True, null=True, verbose_name='ΤΚ')),
                ('cellphone', models.IntegerField(blank=True, null=True, verbose_name='Κινητό')),
                ('phone', models.IntegerField(blank=True, null=True, verbose_name='Σταθερό Τηλεφωνο')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('costumer_submit', models.BooleanField(default=True, verbose_name='Επιβεβαίωση')),
                ('eshop_order_id', models.CharField(blank=True, max_length=10, null=True)),
                ('eshop_session_id', models.CharField(blank=True, max_length=50, null=True)),
                ('printed', models.BooleanField(default=False)),
                ('day_created', models.DateTimeField(blank=True, null=True)),
                ('costumer_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.CostumerAccount', verbose_name='Πελάτης')),
                ('payment_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_manager.PaymentMethod', verbose_name='Τρόπος Πληρωμής')),
                ('seller_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Πωλητής')),
            ],
            managers=[
                ('my_query', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='RetailOrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Τιμή Μονάδας')),
                ('qty', models.DecimalField(decimal_places=2, default=1, max_digits=6, verbose_name='Ποσότητα')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Τιμή Μονάδας')),
                ('day_added', models.DateField(auto_now=True)),
                ('is_find', models.BooleanField(default=False)),
                ('is_return', models.BooleanField(default=False)),
                ('final_price', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='point_of_sale.RetailOrder')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.SizeAttribute')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
            managers=[
                ('my_query', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('content', models.CharField(default='Input here', max_length=300)),
                ('active', models.BooleanField(default=True)),
                ('ordering', models.IntegerField(default=1)),
                ('for_site', models.BooleanField(default=True, verbose_name='Ενεργό για το Site')),
                ('value', models.DecimalField(decimal_places=2, default=5, max_digits=5)),
                ('value_limit', models.DecimalField(decimal_places=2, default=40, max_digits=5)),
            ],
            options={
                'ordering': ['ordering'],
                'verbose_name_plural': 'Τρόποι Αποστολής',
            },
        ),
        migrations.AddField(
            model_name='retailorder',
            name='shipping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='point_of_sale.Shipping'),
        ),
        migrations.AddField(
            model_name='retailorder',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='point_of_sale.OrderStatus'),
        ),
    ]
