# Generated by Django 2.0 on 2018-05-14 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('account', '0003_auto_20180514_1234'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('point_of_sale', '0001_initial'),
        ('dashboard', '0001_initial'),
        ('cart', '0002_auto_20180514_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailorderitem',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.SizeAttribute'),
        ),
        migrations.AddField(
            model_name='retailorderitem',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
        migrations.AddField(
            model_name='retailorder',
            name='cart_related',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.Cart'),
        ),
        migrations.AddField(
            model_name='retailorder',
            name='costumer_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.CostumerAccount', verbose_name='Πελάτης'),
        ),
        migrations.AddField(
            model_name='retailorder',
            name='coupons',
            field=models.ManyToManyField(blank=True, to='cart.Coupons'),
        ),
        migrations.AddField(
            model_name='retailorder',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.PaymentMethod'),
        ),
        migrations.AddField(
            model_name='retailorder',
            name='seller_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Πωλητής'),
        ),
        migrations.AddField(
            model_name='retailorder',
            name='shipping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='point_of_sale.Shipping'),
        ),
        migrations.AddField(
            model_name='retailorder',
            name='store_related',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Store'),
        ),
    ]
