# Generated by Django 2.0 on 2017-12-16 15:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retailorder',
            name='day_created',
        ),
        migrations.AlterField(
            model_name='retailorder',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 16, 17, 7, 53, 742288), verbose_name='Ημερομηνία Δημιουργίας'),
        ),
        migrations.AlterField(
            model_name='retailorder',
            name='order_type',
            field=models.CharField(choices=[('r', 'Λιανική Πώληση'), ('e', 'Eshop'), ('b', 'Επιστροφές'), ('d', 'Καταστροφή Προϊόντων')], default='r', max_length=1),
        ),
        migrations.AlterField(
            model_name='retailorder',
            name='status',
            field=models.CharField(choices=[('1', 'Νέα Παραγγελία'), ('2', 'Σε Επεξεργασία'), ('3', 'Έτοιμο προς Αποστολή'), ('4', 'Απεστάλη'), ('5', 'Επιστράφηκε'), ('6', 'Ακυρώθηκε'), ('7', 'Εισπράκτηκε')], default='1', max_length=1),
        ),
        migrations.DeleteModel(
            name='OrderStatus',
        ),
    ]
