# Generated by Django 2.0 on 2018-05-14 10:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0002_auto_20180514_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailorder',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 14, 13, 6, 20, 297539), verbose_name='Ημερομηνία Δημιουργίας'),
        ),
    ]
