# Generated by Django 2.0.2 on 2018-05-20 11:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0003_auto_20180514_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailorder',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 20, 14, 21, 24, 540529), verbose_name='Ημερομηνία Δημιουργίας'),
        ),
    ]
