# Generated by Django 2.0.2 on 2018-05-20 15:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0004_auto_20180520_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailorder',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 20, 18, 30, 4, 167611), verbose_name='Ημερομηνία Δημιουργίας'),
        ),
    ]
