# Generated by Django 2.0 on 2017-12-16 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0004_auto_20171216_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destroyorder',
            name='seller_account',
        ),
        migrations.RemoveField(
            model_name='destroyorderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='destroyorderitem',
            name='size',
        ),
        migrations.RemoveField(
            model_name='destroyorderitem',
            name='title',
        ),
        migrations.AlterField(
            model_name='retailorder',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 16, 18, 9, 54, 149690), verbose_name='Ημερομηνία Δημιουργίας'),
        ),
        migrations.DeleteModel(
            name='DestroyOrder',
        ),
        migrations.DeleteModel(
            name='DestroyOrderItem',
        ),
    ]
