# Generated by Django 2.0 on 2018-05-21 13:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0005_auto_20180520_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailorder',
            name='order_related',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='point_of_sale.RetailOrder'),
        ),
        migrations.AlterField(
            model_name='retailorder',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 21, 16, 34, 52, 703945), verbose_name='Ημερομηνία Δημιουργίας'),
        ),
    ]
