# Generated by Django 2.0 on 2017-12-18 05:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0005_auto_20171216_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailorder',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 18, 7, 44, 53, 732069), verbose_name='Ημερομηνία Δημιουργίας'),
        ),
    ]
