# Generated by Django 2.0 on 2017-12-18 05:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0006_auto_20171218_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailorder',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 18, 7, 50, 52, 221485), verbose_name='Ημερομηνία Δημιουργίας'),
        ),
    ]
