# Generated by Django 2.0 on 2017-12-18 16:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0008_auto_20171218_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailorder',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 18, 18, 43, 26, 48449), verbose_name='Ημερομηνία Δημιουργίας'),
        ),
    ]
