# Generated by Django 2.0 on 2017-12-19 06:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0009_auto_20171218_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailorder',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 19, 8, 54, 20, 290143), verbose_name='Ημερομηνία Δημιουργίας'),
        ),
    ]
