# Generated by Django 2.0 on 2017-12-19 08:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0010_auto_20171219_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailorder',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 19, 10, 27, 33, 52859), verbose_name='Ημερομηνία Δημιουργίας'),
        ),
    ]
