# Generated by Django 2.0 on 2017-12-19 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0012_auto_20171219_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailorder',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 19, 16, 38, 53, 945385), verbose_name='Ημερομηνία Δημιουργίας'),
        ),
    ]
