# Generated by Django 2.0 on 2017-12-21 07:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0014_auto_20171219_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailorder',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 21, 9, 26, 8, 71077), verbose_name='Ημερομηνία Δημιουργίας'),
        ),
    ]
