# Generated by Django 2.0 on 2017-12-21 07:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0015_auto_20171221_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailorder',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 21, 9, 35, 36, 247811), verbose_name='Ημερομηνία Δημιουργίας'),
        ),
    ]
