# Generated by Django 2.0 on 2017-12-22 06:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0016_auto_20171221_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailorder',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 22, 8, 21, 29, 734799), verbose_name='Ημερομηνία Δημιουργίας'),
        ),
    ]
