# Generated by Django 2.0 on 2017-12-22 06:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0017_auto_20171222_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailorder',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 22, 8, 46, 7, 150407), verbose_name='Ημερομηνία Δημιουργίας'),
        ),
    ]
