# Generated by Django 2.0 on 2017-12-22 13:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0018_auto_20171222_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailorder',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 22, 15, 22, 50, 490647), verbose_name='Ημερομηνία Δημιουργίας'),
        ),
    ]
