# Generated by Django 2.0 on 2017-12-22 13:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0019_auto_20171222_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailorder',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 22, 15, 23, 32, 808245), verbose_name='Ημερομηνία Δημιουργίας'),
        ),
    ]
