# Generated by Django 2.0 on 2017-12-22 21:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0021_auto_20171222_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailorder',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 22, 23, 7, 20, 926493), verbose_name='Ημερομηνία Δημιουργίας'),
        ),
    ]
