# Generated by Django 2.0 on 2017-12-23 08:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0022_auto_20171222_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailorder',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 23, 10, 29, 16, 685123), verbose_name='Ημερομηνία Δημιουργίας'),
        ),
    ]
