# Generated by Django 2.0 on 2017-12-23 10:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_store'),
        ('point_of_sale', '0023_auto_20171223_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailorder',
            name='shop_related',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Store'),
        ),
        migrations.AlterField(
            model_name='retailorder',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 23, 12, 16, 16, 178261), verbose_name='Ημερομηνία Δημιουργίας'),
        ),
    ]
