# Generated by Django 2.0 on 2017-12-23 10:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0024_auto_20171223_1216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='retailorder',
            old_name='shop_related',
            new_name='store_related',
        ),
        migrations.AlterField(
            model_name='retailorder',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 23, 12, 18, 5, 351783), verbose_name='Ημερομηνία Δημιουργίας'),
        ),
    ]
