# Generated by Django 2.0 on 2017-12-24 07:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0026_auto_20171223_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailorder',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 24, 9, 22, 55, 403763), verbose_name='Ημερομηνία Δημιουργίας'),
        ),
    ]
