# Generated by Django 2.0 on 2017-12-24 12:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0027_auto_20171224_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailorder',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='retailorder',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 24, 14, 25, 15, 593599), verbose_name='Ημερομηνία Δημιουργίας'),
        ),
    ]
