# Generated by Django 2.0 on 2017-12-28 07:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0029_auto_20171227_0752'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='retailorder',
            options={'ordering': ['-date_created'], 'verbose_name_plural': '1. Παραστατικά Πωλήσεων'},
        ),
        migrations.AlterField(
            model_name='retailorder',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 28, 9, 45, 55, 137116), verbose_name='Ημερομηνία Δημιουργίας'),
        ),
    ]
