# Generated by Django 2.0 on 2017-12-28 14:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0030_auto_20171228_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailorder',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 28, 16, 26, 42, 760527), verbose_name='Ημερομηνία Δημιουργίας'),
        ),
    ]
