# Generated by Django 2.0 on 2017-12-31 07:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0033_auto_20171231_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailorder',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 31, 9, 18, 40, 478967), verbose_name='Ημερομηνία Δημιουργίας'),
        ),
    ]
