# Generated by Django 2.0 on 2017-12-31 07:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0034_auto_20171231_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailorder',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 31, 9, 21, 4, 613604), verbose_name='Ημερομηνία Δημιουργίας'),
        ),
    ]
