# Generated by Django 2.0 on 2018-02-27 07:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0036_auto_20180107_0901'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='retailorderitem',
            options={'verbose_name_plural': '2. Προϊόντα Πωληθέντα'},
        ),
        migrations.AlterField(
            model_name='retailorder',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 27, 9, 4, 41, 594502), verbose_name='Ημερομηνία Δημιουργίας'),
        ),
    ]
