# Generated by Django 2.0 on 2018-03-02 05:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0038_auto_20180227_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailorder',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 2, 7, 21, 35, 99964), verbose_name='Ημερομηνία Δημιουργίας'),
        ),
    ]
