# Generated by Django 2.0 on 2018-03-02 05:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0039_auto_20180302_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailorder',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 2, 7, 49, 13, 594468), verbose_name='Ημερομηνία Δημιουργίας'),
        ),
    ]
