# Generated by Django 2.0 on 2018-03-07 06:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0040_auto_20180302_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailorder',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 7, 8, 53, 7, 61353), verbose_name='Ημερομηνία Δημιουργίας'),
        ),
    ]
