# Generated by Django 2.0 on 2018-03-18 08:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0041_auto_20180307_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailorder',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 18, 10, 47, 34, 713824), verbose_name='Ημερομηνία Δημιουργίας'),
        ),
    ]
