# Generated by Django 2.0 on 2018-03-18 12:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0043_auto_20180318_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailorder',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 18, 14, 26, 31, 36954), verbose_name='Ημερομηνία Δημιουργίας'),
        ),
    ]
