# Generated by Django 2.0.2 on 2018-03-18 21:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0045_auto_20180318_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailorder',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 18, 23, 6, 23, 6629), verbose_name='Ημερομηνία Δημιουργίας'),
        ),
    ]
