# Generated by Django 2.0 on 2018-03-19 05:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_cart_final_value'),
        ('point_of_sale', '0046_auto_20180318_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailorder',
            name='cart_related',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.Cart'),
        ),
        migrations.AddField(
            model_name='retailorder',
            name='coupons',
            field=models.ManyToManyField(blank=True, to='cart.Coupons'),
        ),
        migrations.AlterField(
            model_name='retailorder',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 19, 7, 7, 35, 752338), verbose_name='Ημερομηνία Δημιουργίας'),
        ),
    ]
