# Generated by Django 2.0 on 2018-03-19 05:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0047_auto_20180319_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailorder',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 19, 7, 37, 39, 945079), verbose_name='Ημερομηνία Δημιουργίας'),
        ),
    ]
