# Generated by Django 2.0 on 2018-03-19 06:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0048_auto_20180319_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailorder',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 19, 8, 37, 41, 715367), verbose_name='Ημερομηνία Δημιουργίας'),
        ),
    ]
