# Generated by Django 2.0 on 2018-03-19 06:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0049_auto_20180319_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailorder',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 19, 8, 39, 32, 613345), verbose_name='Ημερομηνία Δημιουργίας'),
        ),
    ]
