# Generated by Django 2.0 on 2018-03-20 06:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0050_auto_20180319_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailorder',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 20, 8, 11, 16, 643102), verbose_name='Ημερομηνία Δημιουργίας'),
        ),
    ]
