# Generated by Django 2.0.3 on 2018-03-26 06:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0051_auto_20180320_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailorder',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 26, 9, 51, 38, 502154), verbose_name='Ημερομηνία Δημιουργίας'),
        ),
    ]
