# Generated by Django 2.0.3 on 2018-04-22 11:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0053_auto_20180419_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailorder',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 22, 14, 39, 33, 875711), verbose_name='Ημερομηνία Δημιουργίας'),
        ),
        migrations.AlterField(
            model_name='retailorder',
            name='order_type',
            field=models.CharField(choices=[('r', 'Λιανική Πώληση'), ('e', 'Eshop'), ('b', 'Επιστροφές'), ('d', 'Καταστροφή Προϊόντων'), ('wa', 'Παραστατικό Εισαγωγής'), ('wr', 'Παραστατικό Εξαγωγής')], default='r', max_length=1),
        ),
        migrations.AlterField(
            model_name='retailorder',
            name='status',
            field=models.CharField(choices=[('1', 'Νέα Παραγγελία'), ('2', 'Σε Επεξεργασία'), ('3', 'Έτοιμο προς Αποστολή'), ('4', 'Απεστάλη'), ('5', 'Επιστράφηκε'), ('6', 'Ακυρώθηκε'), ('7', 'Εισπράκτηκε'), ('8', 'Ολοκληρώθηκε')], default='1', max_length=1),
        ),
    ]
