# Generated by Django 2.0.2 on 2018-04-29 05:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0054_auto_20180422_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailorder',
            name='cellphone',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Κινητό'),
        ),
        migrations.AlterField(
            model_name='retailorder',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 29, 8, 47, 14, 44479), verbose_name='Ημερομηνία Δημιουργίας'),
        ),
        migrations.AlterField(
            model_name='retailorder',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Σταθερό Τηλεφωνο'),
        ),
    ]
