# Generated by Django 2.0.2 on 2018-04-30 05:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0055_auto_20180429_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailorder',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 30, 8, 51, 51, 961020), verbose_name='Ημερομηνία Δημιουργίας'),
        ),
    ]
