# Generated by Django 2.0.2 on 2018-05-03 04:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0058_auto_20180503_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailorder',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 3, 7, 57, 8, 181261), verbose_name='Ημερομηνία Δημιουργίας'),
        ),
    ]
