# Generated by Django 2.0 on 2018-05-03 10:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0059_auto_20180503_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailorder',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 3, 13, 6, 37, 316077), verbose_name='Ημερομηνία Δημιουργίας'),
        ),
    ]
