# Generated by Django 2.0.3 on 2018-05-09 20:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0060_auto_20180503_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailorder',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 9, 23, 59, 17, 977734), verbose_name='Ημερομηνία Δημιουργίας'),
        ),
    ]
