# Generated by Django 2.0.3 on 2018-05-09 21:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0061_auto_20180509_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailorder',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 10, 0, 5, 29, 563363), verbose_name='Ημερομηνία Δημιουργίας'),
        ),
    ]
