# Generated by Django 2.0.2 on 2018-05-10 04:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0062_auto_20180510_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailorder',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 10, 7, 33, 18, 191755), verbose_name='Ημερομηνία Δημιουργίας'),
        ),
    ]
