# Generated by Django 2.0 on 2018-06-07 11:07

import cart.models
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('id_session', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[cart.models.validate_positive_decimal])),
                ('is_complete', models.BooleanField(default=False)),
                ('payment_method', models.CharField(choices=[('1', 'Μετρητά'), ('2', 'Τραπεζική Κατάθεση'), ('3', 'Πιστωτική Κάρτα'), ('4', 'Paypal')], default='a', max_length=1)),
                ('coupon_discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('final_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'ordering': ['-id'],
            },
            managers=[
                ('my_query', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_session', models.CharField(max_length=50)),
                ('qty', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[cart.models.validate_positive_decimal])),
                ('price_discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[cart.models.validate_positive_decimal])),
                ('final_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[cart.models.validate_positive_decimal])),
            ],
            managers=[
                ('my_query', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='CartRules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_value', models.PositiveIntegerField(default=0)),
                ('shipping_value', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coupons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=50, null=True, unique=True)),
                ('date_created', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('cart_total_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount_percent', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Coupons',
                'ordering': ['active'],
            },
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[cart.models.validate_positive_decimal])),
                ('active_cost', models.BooleanField(default=True)),
                ('active_minimum_cost', models.DecimalField(decimal_places=2, default=40, max_digits=6, validators=[cart.models.validate_positive_decimal])),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Country')),
            ],
        ),
    ]
