# Generated by Django 2.0 on 2018-06-07 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupons',
            name='categories',
            field=models.ManyToManyField(blank=True, to='products.CategorySite'),
        ),
        migrations.AddField(
            model_name='coupons',
            name='products',
            field=models.ManyToManyField(blank=True, to='products.Product'),
        ),
        migrations.AddField(
            model_name='cartrules',
            name='cart',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cart.Cart'),
        ),
        migrations.AddField(
            model_name='cartrules',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.Country'),
        ),
        migrations.AddField(
            model_name='cartrules',
            name='coupons',
            field=models.ManyToManyField(to='cart.Coupons'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='characteristic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.SizeAttribute'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='order_related',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Cart'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product_related',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='coupon',
            field=models.ManyToManyField(blank=True, to='cart.Coupons'),
        ),
        migrations.AddField(
            model_name='cart',
            name='shipping_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.Shipping'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
