# Generated by Django 2.0 on 2018-03-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20180318_1047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupons',
            options={'ordering': ['active'], 'verbose_name_plural': 'Coupons'},
        ),
        migrations.AlterField(
            model_name='coupons',
            name='categories',
            field=models.ManyToManyField(blank=True, to='products.CategorySite'),
        ),
        migrations.AlterField(
            model_name='coupons',
            name='products',
            field=models.ManyToManyField(blank=True, to='products.Product'),
        ),
    ]
