# Generated by Django 2.0 on 2018-03-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20180318_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='coupon',
            field=models.ManyToManyField(blank=True, to='cart.Coupons'),
        ),
        migrations.AddField(
            model_name='coupons',
            name='code',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
