# Generated by Django 2.0 on 2018-03-19 05:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_cart_final_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupons',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 3, 19, 7, 37, 58, 952268)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coupons',
            name='date_end',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 3, 19, 7, 38, 3, 224309)),
            preserve_default=False,
        ),
    ]
