# Generated by Django 2.0 on 2018-03-19 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_auto_20180319_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupons',
            name='date_created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='coupons',
            name='date_end',
            field=models.DateTimeField(),
        ),
    ]
