# Generated by Django 2.0 on 2018-05-14 10:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_manager', '0002_auto_20180514_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='day_created',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2018, 5, 14, 13, 6, 20, 264538), verbose_name='Ημερομηνία'),
        ),
    ]
