# Generated by Django 2.0 on 2017-12-16 10:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_manager', '0004_auto_20171216_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='final_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Τελική Αξία'),
        ),
        migrations.AlterField(
            model_name='order',
            name='day_created',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2017, 12, 16, 12, 18, 53, 673386)),
        ),
    ]
