# Generated by Django 2.0.2 on 2018-05-20 15:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_manager', '0004_auto_20180520_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='day_created',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2018, 5, 20, 18, 30, 4, 129106), verbose_name='Ημερομηνία'),
        ),
    ]
