# Generated by Django 2.0 on 2018-05-21 13:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_manager', '0005_auto_20180520_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='day_created',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2018, 5, 21, 16, 34, 52, 678944), verbose_name='Ημερομηνία'),
        ),
    ]
