# Generated by Django 2.0 on 2017-12-16 15:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0003_auto_20171216_1713'),
        ('inventory_manager', '0006_auto_20171216_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='payment_group',
        ),
        migrations.RemoveField(
            model_name='payorders',
            name='payment_type',
        ),
        migrations.AlterField(
            model_name='order',
            name='day_created',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2017, 12, 16, 17, 13, 50, 181187)),
        ),
        migrations.AlterField(
            model_name='payorders',
            name='payment_method',
            field=models.CharField(choices=[('1', 'Μετρητά'), ('2', 'Τραπεζική Κατάθεση'), ('3', 'Πιστωτική Κάρτα'), ('4', 'Paypal')], default='3', max_length=1),
        ),
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
        migrations.DeleteModel(
            name='PaymentMethodGroup',
        ),
    ]
