# Generated by Django 2.0 on 2017-12-16 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_manager', '0008_auto_20171216_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='day_created',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2017, 12, 16, 18, 9, 54, 99183)),
        ),
    ]
