# Generated by Django 2.0 on 2017-12-18 05:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_manager', '0010_auto_20171218_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='day_created',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2017, 12, 18, 7, 50, 52, 191975)),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='taxes',
            field=models.CharField(choices=[('1', '13'), ('2', '23'), ('3', '24'), ('4', '0')], default='3', max_length=1),
        ),
    ]
