# Generated by Django 2.0 on 2017-12-18 16:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_manager', '0012_auto_20171218_1427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='credit_balance',
            new_name='paid_value',
        ),
        migrations.AlterField(
            model_name='order',
            name='day_created',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2017, 12, 18, 18, 43, 25, 985802)),
        ),
    ]
