# Generated by Django 2.0 on 2017-12-19 08:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_manager', '0014_auto_20171219_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='day_created',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2017, 12, 19, 10, 27, 33, 25355)),
        ),
    ]
