# Generated by Django 2.0 on 2017-12-19 13:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_manager', '0015_auto_20171219_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='day_created',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2017, 12, 19, 15, 25, 22, 963092)),
        ),
    ]
