# Generated by Django 2.0 on 2017-12-19 14:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_manager', '0017_auto_20171219_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='day_created',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2017, 12, 19, 16, 43, 3, 150639)),
        ),
    ]
