# Generated by Django 2.0 on 2017-12-21 07:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_manager', '0018_auto_20171219_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='final_value',
        ),
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='day_created',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2017, 12, 21, 9, 26, 8, 41555)),
        ),
    ]
