# Generated by Django 2.0 on 2017-12-21 07:35

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20171218_0744'),
        ('inventory_manager', '0019_auto_20171221_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_expired', models.DateField(default=datetime.datetime(2017, 12, 21, 7, 35, 36, 233305, tzinfo=utc))),
                ('payment_type', models.CharField(choices=[('1', 'Μετρητά'), ('2', 'Τραπεζική Κατάθεση'), ('3', 'Πιστωτική Κάρτα'), ('4', 'Paypal')], default='1', max_length=1)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('bank', models.CharField(choices=[('0', 'No Bank'), ('1', 'Εθνική Τράπεζα'), ('2', 'Τράπεζα Πειραιώς'), ('3', 'Interamerican')], default='0', max_length=1)),
                ('is_paid', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='day_created',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2017, 12, 21, 9, 35, 36, 219808)),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='order_related',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_manager.Order'),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='vendor_related',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.Supply'),
        ),
    ]
