# Generated by Django 2.0 on 2017-12-22 06:21

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_manager', '0020_auto_20171221_0935'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Unit',
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': '1. Τιμολόγια'},
        ),
        migrations.AlterField(
            model_name='order',
            name='day_created',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2017, 12, 22, 8, 21, 29, 716800)),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Πληρώθηκε'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Πληρωμένο Ποσό'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='discount',
            field=models.IntegerField(default=0, verbose_name='Εκπτωση %'),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='date_expired',
            field=models.DateField(default=datetime.datetime(2017, 12, 22, 6, 21, 29, 718300, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='vendor_related',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Supply'),
        ),
    ]
