# Generated by Django 2.0 on 2017-12-22 06:46

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_manager', '0021_auto_20171222_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='day_created',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2017, 12, 22, 8, 46, 7, 130905)),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='date_expired',
            field=models.DateField(default=datetime.datetime(2017, 12, 22, 6, 46, 7, 132905, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='order_related',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_manager.Order'),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='vendor_related',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Supply'),
        ),
    ]
