# Generated by Django 2.0 on 2017-12-22 13:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_manager', '0022_auto_20171222_0846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentorder',
            name='order_related',
        ),
        migrations.RemoveField(
            model_name='paymentorder',
            name='vendor_related',
        ),
        migrations.AlterField(
            model_name='order',
            name='day_created',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2017, 12, 22, 15, 22, 50, 480647)),
        ),
        migrations.DeleteModel(
            name='PaymentOrder',
        ),
    ]
