# Generated by Django 2.0 on 2017-12-23 08:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_manager', '0026_auto_20171222_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='day_created',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2017, 12, 23, 10, 29, 16, 675122), verbose_name='Ημερομηνία'),
        ),
    ]
