# Generated by Django 2.0 on 2017-12-23 10:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_manager', '0027_auto_20171223_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='day_created',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2017, 12, 23, 12, 16, 16, 163261), verbose_name='Ημερομηνία'),
        ),
    ]
