# Generated by Django 2.0 on 2017-12-23 13:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_manager', '0029_auto_20171223_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='day_created',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2017, 12, 23, 15, 18, 57, 139177), verbose_name='Ημερομηνία'),
        ),
    ]
