# Generated by Django 2.0 on 2017-12-24 12:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_manager', '0031_auto_20171224_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='day_created',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2017, 12, 24, 14, 25, 15, 583599), verbose_name='Ημερομηνία'),
        ),
    ]
