# Generated by Django 2.0 on 2017-12-28 07:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_manager', '0033_auto_20171227_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='day_created',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2017, 12, 28, 9, 45, 54, 962329), verbose_name='Ημερομηνία'),
        ),
    ]
