# Generated by Django 2.0 on 2017-12-28 14:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_manager', '0034_auto_20171228_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='day_created',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2017, 12, 28, 16, 26, 42, 746527), verbose_name='Ημερομηνία'),
        ),
    ]
