# Generated by Django 2.0 on 2017-12-31 07:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_manager', '0036_auto_20171231_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='day_created',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2017, 12, 31, 9, 21, 4, 587098), verbose_name='Ημερομηνία'),
        ),
    ]
