# Generated by Django 2.0 on 2018-02-27 07:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_manager', '0039_auto_20180227_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='day_created',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2018, 2, 27, 9, 24, 51, 87110), verbose_name='Ημερομηνία'),
        ),
    ]
