# Generated by Django 2.0 on 2018-03-02 05:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_manager', '0040_auto_20180227_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='day_created',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2018, 3, 2, 7, 21, 35, 71960), verbose_name='Ημερομηνία'),
        ),
    ]
