# Generated by Django 2.0 on 2018-03-18 12:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_manager', '0044_auto_20180318_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='day_created',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2018, 3, 18, 14, 22, 46, 931179), verbose_name='Ημερομηνία'),
        ),
    ]
