# Generated by Django 2.0 on 2018-03-18 12:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_manager', '0045_auto_20180318_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='day_created',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2018, 3, 18, 14, 26, 31, 12451), verbose_name='Ημερομηνία'),
        ),
    ]
