# Generated by Django 2.0 on 2018-03-19 05:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_manager', '0048_auto_20180318_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='day_created',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2018, 3, 19, 7, 7, 35, 722332), verbose_name='Ημερομηνία'),
        ),
    ]
