# Generated by Django 2.0 on 2018-03-19 05:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_manager', '0049_auto_20180319_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='day_created',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2018, 3, 19, 7, 37, 39, 905074), verbose_name='Ημερομηνία'),
        ),
    ]
