# Generated by Django 2.0 on 2018-03-19 06:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_manager', '0050_auto_20180319_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='day_created',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2018, 3, 19, 8, 37, 41, 684868), verbose_name='Ημερομηνία'),
        ),
    ]
