# Generated by Django 2.0 on 2018-03-19 06:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_manager', '0051_auto_20180319_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='day_created',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2018, 3, 19, 8, 39, 32, 581833), verbose_name='Ημερομηνία'),
        ),
    ]
