# Generated by Django 2.0.3 on 2018-03-26 06:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_manager', '0053_auto_20180320_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='day_created',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2018, 3, 26, 9, 51, 38, 402495), verbose_name='Ημερομηνία'),
        ),
    ]
