# Generated by Django 2.0.2 on 2018-04-30 05:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_manager', '0057_auto_20180429_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='day_created',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2018, 4, 30, 8, 51, 51, 921016), verbose_name='Ημερομηνία'),
        ),
    ]
