# Generated by Django 2.0.3 on 2018-05-09 20:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_manager', '0064_auto_20180503_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='day_created',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2018, 5, 9, 23, 59, 17, 872568), verbose_name='Ημερομηνία'),
        ),
    ]
