# Generated by Django 2.0.3 on 2018-05-09 21:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_manager', '0065_auto_20180509_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='day_created',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2018, 5, 10, 0, 5, 29, 457691), verbose_name='Ημερομηνία'),
        ),
    ]
