# Generated by Django 2.0.2 on 2018-05-10 04:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_manager', '0066_auto_20180510_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='day_created',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2018, 5, 10, 7, 33, 18, 156250), verbose_name='Ημερομηνία'),
        ),
    ]
