# Generated by Django 2.0 on 2017-12-16 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category_site',
            field=models.ManyToManyField(blank=True, null=True, to='products.CategorySite'),
        ),
    ]
