# Generated by Django 2.0 on 2018-05-14 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorysite',
            name='title',
            field=models.CharField(max_length=120),
        ),
    ]
