# Generated by Django 2.0.2 on 2018-05-20 11:21

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20180514_1306'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supply',
            options={'ordering': ['title'], 'verbose_name_plural': '9. Προμηθευτές'},
        ),
        migrations.AlterModelManagers(
            name='sizeattribute',
            managers=[
                ('my_query', django.db.models.manager.Manager()),
            ],
        ),
    ]
