# Generated by Django 2.0 on 2017-12-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20171216_1039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='day_added',
            new_name='date_created',
        ),
        migrations.RemoveField(
            model_name='brands',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='brands',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='categorysite',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='categorysite',
            name='seo_keyword',
        ),
        migrations.RemoveField(
            model_name='categorysite',
            name='sort_order',
        ),
        migrations.RemoveField(
            model_name='categorysite',
            name='status',
        ),
        migrations.AddField(
            model_name='brands',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Ενεργοποίηση'),
        ),
        migrations.AddField(
            model_name='categorysite',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='size',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='supply',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='measure_unit',
            field=models.CharField(blank=True, choices=[('1', 'Τεμάχια'), ('2', 'Κιλά'), ('3', 'Κιβώτια')], default='1', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('1', 'Σε απόθεμα'), ('2', 'Inactive'), ('3', 'Διαθέσιμο με παραγγελία'), ('4', 'Προσωρινά μη διαθέσιμο')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='supply',
            name='taxes_modifier',
            field=models.CharField(choices=[('1', '13'), ('2', '23'), ('3', '24'), ('4', '0')], default='3', max_length=1),
        ),
    ]
