# Generated by Django 2.0 on 2017-12-18 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20171216_1708'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title'], 'verbose_name': '3. Κατηγορίες Αποθήκης', 'verbose_name_plural': '3. Κατηγορίες Αποθήκης'},
        ),
        migrations.AlterField(
            model_name='sizeattribute',
            name='product_related',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product', verbose_name='Προϊόν'),
        ),
        migrations.AlterField(
            model_name='sizeattribute',
            name='qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Ποσότητα'),
        ),
        migrations.AlterField(
            model_name='sizeattribute',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Size', verbose_name='Νούμερο'),
        ),
    ]
