# Generated by Django 2.0 on 2017-12-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20171218_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands',
            name='title',
            field=models.CharField(max_length=120, verbose_name='Ονομασία Brand'),
        ),
    ]
