# Generated by Django 2.0 on 2018-02-27 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20171223_1518'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id'], 'verbose_name_plural': '1. Προϊόντα'},
        ),
        migrations.AlterModelOptions(
            name='supply',
            options={'ordering': ['id'], 'verbose_name_plural': '9. Προμηθευτές'},
        ),
    ]
