# Generated by Django 2.0 on 2018-03-07 06:53

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_categorysite_show_on_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorysite',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.CategorySite', verbose_name='parent'),
        ),
        migrations.AlterField(
            model_name='categorysite',
            name='show_on_menu',
            field=models.BooleanField(default=False, verbose_name='Active on Navbar'),
        ),
    ]
