# Generated by Django 2.0.3 on 2018-03-26 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20180307_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='different_color',
            field=models.ManyToManyField(blank=True, related_name='_product_different_color_+', to='products.Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='related_products',
            field=models.ManyToManyField(blank=True, related_name='_product_related_products_+', to='products.Product'),
        ),
    ]
