# Generated by Django 2.0.3 on 2018-05-09 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20180419_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorysite',
            name='level',
        ),
        migrations.RemoveField(
            model_name='categorysite',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='categorysite',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='categorysite',
            name='tree_id',
        ),
        migrations.AddField(
            model_name='categorysite',
            name='ordering',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='categorysite',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.CategorySite'),
        ),
    ]
