# Generated by Django 2.0.3 on 2018-05-09 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20180509_2359'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorysite',
            options={'ordering': ['order'], 'verbose_name_plural': '3. Κατηγορίες Site'},
        ),
        migrations.RemoveField(
            model_name='categorysite',
            name='ordering',
        ),
        migrations.AddField(
            model_name='categorysite',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
