# Generated by Django 2.0.2 on 2018-05-10 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20180510_0005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorysite',
            options={'ordering': ['-order'], 'verbose_name_plural': '3. Κατηγορίες Site'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'ordering': ['-ordering'], 'verbose_name_plural': '5. Χρώματα'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'ordering': ['-ordering'], 'verbose_name_plural': '6. Μεγέθη'},
        ),
        migrations.RemoveField(
            model_name='color',
            name='level',
        ),
        migrations.RemoveField(
            model_name='color',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='color',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='color',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='color',
            name='tree_id',
        ),
        migrations.RemoveField(
            model_name='size',
            name='level',
        ),
        migrations.RemoveField(
            model_name='size',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='size',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='size',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='size',
            name='tree_id',
        ),
        migrations.AddField(
            model_name='color',
            name='ordering',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='size',
            name='ordering',
            field=models.PositiveIntegerField(default=1, help_text='Bigger goes first'),
        ),
    ]
